In [29]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # plotting

from transformers import BertModel
import torch

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ai-mix-v26/train_essays.parquet
/kaggle/input/ai-mix-v26/valid_essays.parquet
/kaggle/input/llm-detect-ai-generated-text/sample_submission.csv
/kaggle/input/llm-detect-ai-generated-text/train_prompts.csv
/kaggle/input/llm-detect-ai-generated-text/test_essays.csv
/kaggle/input/llm-detect-ai-generated-text/train_essays.csv


In [8]:
# get datasets 
prompts = pd.read_csv("/kaggle/input/llm-detect-ai-generated-text/train_prompts.csv")
test = pd.read_csv("/kaggle/input/llm-detect-ai-generated-text/test_essays.csv")
train = pd.read_csv("/kaggle/input/llm-detect-ai-generated-text/train_essays.csv")

# Notes about data:
Two prompts:
'Write an explanatory essay to inform fellow citizens about the advantages of limiting car usage. Your essay must be based on ideas and information that can be found in the passage set. Manage your time carefully so that you can read the passages; plan your response; write your response; and revise and edit your response. Be sure to use evidence from multiple sources; and avoid overly relying on one source. Your response should be in the form of a multiparagraph essay. Write your essay in the space provided.'

'Write a letter to your state senator in which you argue in favor of keeping the Electoral College or changing to election by popular vote for the president of the United States. Use the information from the texts in your essay. Manage your time carefully so that you can read the passages; plan your response; write your response; and revise and edit your response. Be sure to include a claim; address counterclaims; use evidence from multiple sources; and avoid overly relying on one source. Your response should be in the form of a multiparagraph essay. Write your response in the space provided.'



In [25]:
# prompts['instructions'][1]

train['generated'].value_counts().values


array([1375,    3])

In [10]:
test

id  prompt_id          text
0  0000aaaa          2  Aaa bbb ccc.
1  1111bbbb          3  Bbb ccc ddd.
2  2222cccc          4  CCC ddd eee.

# Note: Only 3 generated essays
Goal: import more generated essay data from an external dataset:
Datamix (https://www.kaggle.com/datasets/conjuring92/ai-mix-v26/data)

In [4]:
# load datamix
df = pd.read_parquet('/kaggle/input/ai-mix-v26')

In [6]:
df['generated'].value_counts().values # 130834 human, 36612 generated

array([130834,  36612])

In [18]:
df

id  prompt_id  \
0       e_ddxvqx5i          0   
1       e_hi0yzrcv          0   
2       e_uesv4xha          0   
3       e_2tl5ylwy          0   
4       e_s6ci4vj0          0   
...            ...        ...   
167441  e_ztvzemgq        103   
167442  e_vii16yc6        103   
167443  e_yqi87ctp        103   
167444  e_7659fil7        103   
167445  e_nmisouia        103   

                                                     text  generated  
0       In recent years, there has been a growing move...          1  
1       ---\nWhy not cars in our life\n===============...          1  
2       A car is considered by many a nessecity for ev...          1  
3       H\n\nello fellow citezens , we are here to inf...          0  
4       Have you ever known how if feels not being abl...          1  
...                                                   ...        ...  
167441  He stood there, looking at his own grave. The ...          1  
167442  Crummable.\n*What a crummy word* she thought, ...          0  
167443  Title: The Awakening in a Different Realm\nWor...          1  
167444  Title: The Timekeeper's Descent\nSilence engul...          1  
167445  Captain's Log, Stardate 53120.3\nThe universe ...          1  

[167446 rows x 4 columns]

In [17]:
train

id  prompt_id                                               text  \
0     0059830c          0  Cars. Cars have been around since they became ...   
1     005db917          0  Transportation is a large necessity in most co...   
2     008f63e3          0  "America's love affair with it's vehicles seem...   
3     00940276          0  How often do you ride in a car? Do you drive a...   
4     00c39458          0  Cars are a wonderful thing. They are perhaps o...   
...        ...        ...                                                ...   
1373  fe6ff9a5          1  There has been a fuss about the Elector Colleg...   
1374  ff669174          0  Limiting car usage has many advantages. Such a...   
1375  ffa247e0          0  There's a new trend that has been developing f...   
1376  ffc237e9          0  As we all know cars are a big part of our soci...   
1377  ffe1ca0d          0  Cars have been around since the 1800's and hav...   

      generated  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
1373          0  
1374          0  
1375          0  
1376          0  
1377          0  

[1378 rows x 4 columns]

In [20]:
datasets = [train, df]
comb_df = pd.concat(datasets)

In [22]:
comb_df['generated'].value_counts().values # 130837 human written, 37987 generated

array([130837,  37987])

# Split train test


In [ ]:
from sklearn.model_selection import train_test_split

t

# Load Model

In [31]:
model = BertModel.from_pretrained("bert-base-uncased", torch_dtype=torch.float16, attn_implementation="sdpa")

In [32]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False